import { useTranslation } from "react-i18next"

const fr = {
  badge: "En direct",
  join: "Rejoindre",
  title: "Session en direct",
  intro: "Le formateur est en direct. Rejoignez la session.",
  joinBtn: "Rejoindre le direct",
  none: "Aucun direct en ce moment. Cette page se met à jour dès que le formateur démarre.",
  connecting: "Connexion à la session…",
  ended: "Le direct est terminé ou la connexion a été interrompue.",
  rejoin: "Se reconnecter",
  waiting: "En attente du formateur…",
  reconnecting: "Connexion instable, reconnexion…",
  enableAudio: "Activer le son",
  leave: "Quitter",
  studioTitle: "Direct : studio formateur",
  pageTitle: "Direct",
  pickCourse: "Formation",
  noCourses: "Aucune formation.",
  liveNow: "En direct",
  notLive: "Hors ligne",
  start: "Démarrer le direct",
  stop: "Terminer le direct",
  stopConfirm: "Terminer le direct pour tous les participants ?",
  started: "Direct démarré : la bannière apparaît chez les étudiants en quelques secondes.",
  stopped: "Direct terminé.",
  chatTitle: "Discussion",
  chatEmpty: "Aucun message pour l'instant.",
  chatPlaceholder: "Écrire un message…",
  chatSend: "Envoyer",
  me: "Moi",
  lobbyTitle: "Prêt à rejoindre ?",
  lobbyHint: "Vérifiez votre caméra et votre micro avant d'entrer.",
  camera: "Caméra",
  microphone: "Micro",
  screenShare: "Écran",
  stopShare: "Arrêter",
  raiseHand: "Lever la main",
  lowerHand: "Baisser la main",
  handRaised: "Main levée : le formateur a été prévenu.",
  joinNow: "Rejoindre maintenant",
  defaultDevice: "Par défaut",
  previewOff: "Caméra désactivée",
  micLevel: "Niveau du micro",
  settings: "Réglages",
  fullscreen: "Plein écran",
  people: "Participants",
  host: "Formateur",
  you: "vous",
  canSpeak: "Peut parler",
  wantsToSpeak: "demande la parole",
  allow: "Donner la parole",
  revoke: "Retirer la parole",
  kick: "Exclure",
  kickConfirm: "Exclure ce participant du direct ?",
  granted: "Le formateur vous a donné la parole : vous pouvez activer micro, caméra et écran.",
  revoked: "Votre prise de parole a été retirée.",
  removed: "Vous avez été retiré du direct par le formateur.",
  duplicate: "Vous êtes connecté depuis un autre appareil ou un autre onglet.",
  endAll: "Terminer pour tous",
  endedByYou: "Vous avez terminé le direct.",
  screenOf: "Écran de",
  youShare: "Vous partagez votre écran",
  errDenied: "Accès refusé. Cliquez sur le cadenas à gauche de l'adresse, autorisez la caméra et le micro, puis rechargez la page.",
  errNotFound: "Aucune caméra ou aucun micro détecté.",
  errBusy: "Le périphérique est utilisé par une autre application.",
  errInsecure: "La caméra et le micro exigent une connexion sécurisée (HTTPS) ou localhost.",
  errScreenUnsupported: "Le partage d'écran n'est pas disponible sur cet appareil.",
  errGeneric: "Impossible d'accéder au périphérique.",
  dismiss: "Fermer",
  shareTitle: "Inviter les étudiants",
  shareLink: "Lien du direct",
  copy: "Copier le lien",
  copied: "Lien copié",
  shareWhatsapp: "WhatsApp",
  shareEmail: "E-mail",
  shareNative: "Partager…",
  shareMessage: "Rejoignez le direct :",
  shareSubject: "Direct :",
  shareOnlyEnrolled: "Seuls les étudiants inscrits à cette formation peuvent entrer.",
  notEnrolled: "Vous n'êtes pas inscrit à cette formation.",
}

const en: typeof fr = {
  badge: "Live",
  join: "Join",
  title: "Live session",
  intro: "The instructor is live. Join the session.",
  joinBtn: "Join the live",
  none: "No live session right now. This page updates as soon as the instructor starts.",
  connecting: "Connecting to the session…",
  ended: "The live has ended or the connection was interrupted.",
  rejoin: "Reconnect",
  waiting: "Waiting for the instructor…",
  reconnecting: "Unstable connection, reconnecting…",
  enableAudio: "Enable sound",
  leave: "Leave",
  studioTitle: "Live: instructor studio",
  pageTitle: "Live",
  pickCourse: "Course",
  noCourses: "No courses.",
  liveNow: "Live",
  notLive: "Offline",
  start: "Start the live",
  stop: "End the live",
  stopConfirm: "End the live for all participants?",
  started: "Live started: the banner shows up for students within seconds.",
  stopped: "Live ended.",
  chatTitle: "Chat",
  chatEmpty: "No messages yet.",
  chatPlaceholder: "Write a message…",
  chatSend: "Send",
  me: "Me",
  lobbyTitle: "Ready to join?",
  lobbyHint: "Check your camera and microphone before entering.",
  camera: "Camera",
  microphone: "Mic",
  screenShare: "Screen",
  stopShare: "Stop",
  raiseHand: "Raise hand",
  lowerHand: "Lower hand",
  handRaised: "Hand raised: the instructor has been notified.",
  joinNow: "Join now",
  defaultDevice: "Default",
  previewOff: "Camera is off",
  micLevel: "Microphone level",
  settings: "Settings",
  fullscreen: "Fullscreen",
  people: "Participants",
  host: "Instructor",
  you: "you",
  canSpeak: "Can speak",
  wantsToSpeak: "wants to speak",
  allow: "Allow to speak",
  revoke: "Take away",
  kick: "Remove",
  kickConfirm: "Remove this participant from the live?",
  granted: "The instructor let you speak: you can now turn on mic, camera and screen.",
  revoked: "Your speaking permission was removed.",
  removed: "You were removed from the live by the instructor.",
  duplicate: "You are connected from another device or tab.",
  endAll: "End for everyone",
  endedByYou: "You ended the live.",
  screenOf: "Screen of",
  youShare: "You are sharing your screen",
  errDenied: "Access denied. Click the padlock next to the address, allow camera and microphone, then reload the page.",
  errNotFound: "No camera or microphone detected.",
  errBusy: "The device is being used by another application.",
  errInsecure: "Camera and microphone require a secure connection (HTTPS) or localhost.",
  errScreenUnsupported: "Screen sharing is not available on this device.",
  errGeneric: "Could not access the device.",
  dismiss: "Close",
  shareTitle: "Invite students",
  shareLink: "Live link",
  copy: "Copy link",
  copied: "Link copied",
  shareWhatsapp: "WhatsApp",
  shareEmail: "Email",
  shareNative: "Share…",
  shareMessage: "Join the live:",
  shareSubject: "Live:",
  shareOnlyEnrolled: "Only students enrolled in this course can enter.",
  notEnrolled: "You are not enrolled in this course.",
}

export type LiveText = typeof fr

export function useLiveText(): LiveText {
  const { i18n } = useTranslation()
  return i18n.language?.startsWith("fr") ? fr : en
}